/* This file was automatically generated by libvirt-wireshark-dissector/util/genxdrdef.pl. *DO NOT MODIFY* this file directly. */
#ifndef _KEEPALIVE_H_
#define _KEEPALIVE_H_
#define KEEPALIVE_PROGRAM (0x6b656570)
#define KEEPALIVE_PROTOCOL_VERSION (1)
static const vir_proc_payload_t keepalive_dissectors[] = {
    { 1, NULL, NULL, NULL },
    { 2, NULL, NULL, NULL },
};
static const value_string keepalive_procedure_strings[] = {
    { 1, "PING" },
    { 2, "PONG" },
    { 0, NULL }
};
#endif /* _KEEPALIVE_H_ */
