/* This file was automatically generated by libvirt-wireshark-dissector/util/genxdrdef.pl. *DO NOT MODIFY* this file directly. */
#ifndef _LXC_H_
#define _LXC_H_
static int hf_lxc_domain_open_namespace_args = -1;
static gint ett_lxc_domain_open_namespace_args = -1;
static gboolean dissect_xdr_lxc_domain_open_namespace_args(tvbuff_t *tvb, proto_item *ti, XDR *xdrs, int hf)
{
    goffset start, incr;
    proto_tree *tree;
    
    start = VIR_HEADER_LEN + xdr_getpos(xdrs);
    tree = proto_item_add_subtree(ti, ett_lxc_domain_open_namespace_args);
    hf = hf_lxc_domain_open_namespace_args;
    
    ti = proto_tree_add_item(tree, hf, tvb, start, -1, ENC_NA);
    proto_item_set_text(ti, "dom: ");
    if (!dissect_xdr_remote_nonnull_domain(tvb, ti, xdrs, hf)) return FALSE;
    incr = xdr_getpos(xdrs) - start + VIR_HEADER_LEN;
    proto_item_set_len(ti, incr);
    start += incr;
    
    ti = proto_tree_add_item(tree, hf, tvb, start, -1, ENC_NA);
    proto_item_set_text(ti, "flags: ");
    if (!dissect_xdr_u_int(tvb, ti, xdrs, hf)) return FALSE;
    incr = xdr_getpos(xdrs) - start + VIR_HEADER_LEN;
    proto_item_set_len(ti, incr);
    start += incr;
    return TRUE;
}
#define LXC_PROGRAM (0x00068000)
#define LXC_PROTOCOL_VERSION (1)
static const vir_proc_payload_t lxc_dissectors[] = {
    { 1, dissect_xdr_lxc_domain_open_namespace_args, NULL, NULL },
};
static const value_string lxc_procedure_strings[] = {
    { 1, "DOMAIN_OPEN_NAMESPACE" },
    { 0, NULL }
};
#endif /* _LXC_H_ */
