/* This file was automatically generated by libvirt-wireshark-dissector/util/genxdrdef.pl. *DO NOT MODIFY* this file directly. */
#ifndef _LXC_H_
#define _LXC_H_
static vir_named_xdrdef_t struct_lxc_domain_open_namespace_args_members_def[] = {
    { "dom", XDR_STRUCT, struct_remote_nonnull_domain_members_def, 0 /* remote_nonnull_domain */ },
    { "flags", XDR_UINT, NULL, 0 /* uint */ },
    VIR_NAMED_XDRDEF_NULL
};
#define LXC_PROGRAM (0x00068000)
#define LXC_PROTOCOL_VERSION (1)
static const vir_proc_payload_t lxc_payload_def[] = {
    { 1, struct_lxc_domain_open_namespace_args_members_def, NULL, NULL },
};
static const value_string lxc_procedure_strings[] = {
    { 1, "DOMAIN_OPEN_NAMESPACE" },
    { 0, NULL }
};
#endif /* _LXC_H_ */
