/* This file was automatically generated by libvirt-wireshark-dissector/util/genxdrdef.pl. *DO NOT MODIFY* this file directly. */
#ifndef _PROTOCOL_H_
#define _PROTOCOL_H_
static const vir_xdrdef_t int_def = {
    XDR_INT, NULL, 0
};
static const vir_xdrdef_t uint_def = {
    XDR_UINT, NULL, 0
};
static const vir_xdrdef_t hyper_def = {
    XDR_HYPER, NULL, 0
};
static const vir_xdrdef_t uhyper_def = {
    XDR_UHYPER, NULL, 0
};
static const vir_xdrdef_t double_def = {
    XDR_DOUBLE, NULL, 0
};
static const vir_xdrdef_t char_def = {
    XDR_CHAR, NULL, 0
};
#include "libvirt/remote.h"
#include "libvirt/qemu.h"
#include "libvirt/lxc.h"
#include "libvirt/keepalive.h"
#define VIR_PROCEDURES_HEADERSET \
        { &hf_remote_procedure,\
          { "procedure", "libvirt.procedure",\
            FT_INT32, BASE_DEC,\
            VALS(remote_procedure_strings), 0x0,\
            NULL, HFILL}\
        },\
        { &hf_qemu_procedure,\
          { "procedure", "libvirt.procedure",\
            FT_INT32, BASE_DEC,\
            VALS(qemu_procedure_strings), 0x0,\
            NULL, HFILL}\
        },\
        { &hf_lxc_procedure,\
          { "procedure", "libvirt.procedure",\
            FT_INT32, BASE_DEC,\
            VALS(lxc_procedure_strings), 0x0,\
            NULL, HFILL}\
        },\
        { &hf_keepalive_procedure,\
          { "procedure", "libvirt.procedure",\
            FT_INT32, BASE_DEC,\
            VALS(keepalive_procedure_strings), 0x0,\
            NULL, HFILL}\
        },
static const value_string program_strings[] = {
    { 0x20008086, "REMOTE" },
    { 0x20008087, "QEMU" },
    { 0x00068000, "LXC" },
    { 0x6b656570, "KEEPALIVE" },
    { 0, NULL }
};
static int hf_remote_procedure = -1;
static int hf_qemu_procedure = -1;
static int hf_lxc_procedure = -1;
static int hf_keepalive_procedure = -1;
#define VIR_PROG_SWITCH(prog)\
switch (prog) {\
case REMOTE_PROGRAM:\
    VIR_PROG_CASE(remote);\
    break;\
case QEMU_PROGRAM:\
    VIR_PROG_CASE(qemu);\
    break;\
case LXC_PROGRAM:\
    VIR_PROG_CASE(lxc);\
    break;\
case KEEPALIVE_PROGRAM:\
    VIR_PROG_CASE(keepalive);\
    break;\
}
#endif /* _PROTOCOL_H_ */
