/* This file was automatically generated by libvirt-wireshark-dissector/util/genxdrdef.pl. *DO NOT MODIFY* this file directly. */
#ifndef _QEMU_H_
#define _QEMU_H_
static vir_named_xdrdef_t struct_qemu_domain_monitor_command_args_members_def[] = {
    { "dom", XDR_STRUCT, struct_remote_nonnull_domain_members_def, 0 /* remote_nonnull_domain */ },
    { "cmd", XDR_STRING, 0, REMOTE_STRING_MAX /* remote_nonnull_string */ },
    { "flags", XDR_UINT, NULL, 0 /* uint */ },
    VIR_NAMED_XDRDEF_NULL
};
static vir_named_xdrdef_t struct_qemu_domain_monitor_command_ret_members_def[] = {
    { "result", XDR_STRING, 0, REMOTE_STRING_MAX /* remote_nonnull_string */ },
    VIR_NAMED_XDRDEF_NULL
};
static vir_named_xdrdef_t struct_qemu_domain_attach_args_members_def[] = {
    { "pid_value", XDR_UINT, NULL, 0 /* uint */ },
    { "flags", XDR_UINT, NULL, 0 /* uint */ },
    VIR_NAMED_XDRDEF_NULL
};
static vir_named_xdrdef_t struct_qemu_domain_attach_ret_members_def[] = {
    { "dom", XDR_STRUCT, struct_remote_nonnull_domain_members_def, 0 /* remote_nonnull_domain */ },
    VIR_NAMED_XDRDEF_NULL
};
static vir_named_xdrdef_t struct_qemu_domain_agent_command_args_members_def[] = {
    { "dom", XDR_STRUCT, struct_remote_nonnull_domain_members_def, 0 /* remote_nonnull_domain */ },
    { "cmd", XDR_STRING, 0, REMOTE_STRING_MAX /* remote_nonnull_string */ },
    { "timeout", XDR_INT, NULL, 0 /* int */ },
    { "flags", XDR_UINT, NULL, 0 /* uint */ },
    VIR_NAMED_XDRDEF_NULL
};
static vir_named_xdrdef_t struct_qemu_domain_agent_command_ret_members_def[] = {
    { "result", XDR_POINTER, &remote_nonnull_string_def, 0 /* remote_string */ },
    VIR_NAMED_XDRDEF_NULL
};
#define QEMU_PROGRAM (0x20008087)
#define QEMU_PROTOCOL_VERSION (1)
static const vir_proc_payload_t qemu_payload_def[] = {
    { 1, struct_qemu_domain_monitor_command_args_members_def, struct_qemu_domain_monitor_command_ret_members_def, NULL },
    { 2, struct_qemu_domain_attach_args_members_def, struct_qemu_domain_attach_ret_members_def, NULL },
    { 3, struct_qemu_domain_agent_command_args_members_def, struct_qemu_domain_agent_command_ret_members_def, NULL },
};
static const value_string qemu_procedure_strings[] = {
    { 1, "DOMAIN_MONITOR_COMMAND" },
    { 2, "DOMAIN_ATTACH" },
    { 3, "DOMAIN_AGENT_COMMAND" },
    { 0, NULL }
};
#endif /* _QEMU_H_ */
