/* This file was automatically generated by libvirt-wireshark-dissector/util/genxdrdef.pl. *DO NOT MODIFY* this file directly. */
#ifndef _QEMU_H_
#define _QEMU_H_
static int hf_qemu_domain_monitor_command_args__dom = -1;
static int hf_qemu_domain_monitor_command_args__cmd = -1;
static int hf_qemu_domain_monitor_command_args__flags = -1;
static int hf_qemu_domain_monitor_command_args = -1;
static gint ett_qemu_domain_monitor_command_args = -1;
static gboolean dissect_xdr_qemu_domain_monitor_command_args(tvbuff_t *tvb, proto_tree *tree, XDR *xdrs, int hf)
{
    goffset start;
    proto_item *ti;
    
    start = VIR_HEADER_LEN + xdr_getpos(xdrs);
    ti = proto_tree_add_item(tree, hf, tvb, start, -1, ENC_NA);
    proto_item_append_text(ti, " :: qemu_domain_monitor_command_args");
    tree = proto_item_add_subtree(ti, ett_qemu_domain_monitor_command_args);
    
    hf = hf_qemu_domain_monitor_command_args__dom;
    if (!dissect_xdr_remote_nonnull_domain(tvb, tree, xdrs, hf)) return FALSE;
    
    hf = hf_qemu_domain_monitor_command_args__cmd;
    if (!dissect_xdr_remote_nonnull_string(tvb, tree, xdrs, hf)) return FALSE;
    
    hf = hf_qemu_domain_monitor_command_args__flags;
    if (!dissect_xdr_u_int(tvb, tree, xdrs, hf)) return FALSE;
    proto_item_set_len(ti, xdr_getpos(xdrs) - start + VIR_HEADER_LEN);
    return TRUE;
}
static int hf_qemu_domain_monitor_command_ret__result = -1;
static int hf_qemu_domain_monitor_command_ret = -1;
static gint ett_qemu_domain_monitor_command_ret = -1;
static gboolean dissect_xdr_qemu_domain_monitor_command_ret(tvbuff_t *tvb, proto_tree *tree, XDR *xdrs, int hf)
{
    goffset start;
    proto_item *ti;
    
    start = VIR_HEADER_LEN + xdr_getpos(xdrs);
    ti = proto_tree_add_item(tree, hf, tvb, start, -1, ENC_NA);
    proto_item_append_text(ti, " :: qemu_domain_monitor_command_ret");
    tree = proto_item_add_subtree(ti, ett_qemu_domain_monitor_command_ret);
    
    hf = hf_qemu_domain_monitor_command_ret__result;
    if (!dissect_xdr_remote_nonnull_string(tvb, tree, xdrs, hf)) return FALSE;
    proto_item_set_len(ti, xdr_getpos(xdrs) - start + VIR_HEADER_LEN);
    return TRUE;
}
static int hf_qemu_domain_attach_args__pid_value = -1;
static int hf_qemu_domain_attach_args__flags = -1;
static int hf_qemu_domain_attach_args = -1;
static gint ett_qemu_domain_attach_args = -1;
static gboolean dissect_xdr_qemu_domain_attach_args(tvbuff_t *tvb, proto_tree *tree, XDR *xdrs, int hf)
{
    goffset start;
    proto_item *ti;
    
    start = VIR_HEADER_LEN + xdr_getpos(xdrs);
    ti = proto_tree_add_item(tree, hf, tvb, start, -1, ENC_NA);
    proto_item_append_text(ti, " :: qemu_domain_attach_args");
    tree = proto_item_add_subtree(ti, ett_qemu_domain_attach_args);
    
    hf = hf_qemu_domain_attach_args__pid_value;
    if (!dissect_xdr_u_int(tvb, tree, xdrs, hf)) return FALSE;
    
    hf = hf_qemu_domain_attach_args__flags;
    if (!dissect_xdr_u_int(tvb, tree, xdrs, hf)) return FALSE;
    proto_item_set_len(ti, xdr_getpos(xdrs) - start + VIR_HEADER_LEN);
    return TRUE;
}
static int hf_qemu_domain_attach_ret__dom = -1;
static int hf_qemu_domain_attach_ret = -1;
static gint ett_qemu_domain_attach_ret = -1;
static gboolean dissect_xdr_qemu_domain_attach_ret(tvbuff_t *tvb, proto_tree *tree, XDR *xdrs, int hf)
{
    goffset start;
    proto_item *ti;
    
    start = VIR_HEADER_LEN + xdr_getpos(xdrs);
    ti = proto_tree_add_item(tree, hf, tvb, start, -1, ENC_NA);
    proto_item_append_text(ti, " :: qemu_domain_attach_ret");
    tree = proto_item_add_subtree(ti, ett_qemu_domain_attach_ret);
    
    hf = hf_qemu_domain_attach_ret__dom;
    if (!dissect_xdr_remote_nonnull_domain(tvb, tree, xdrs, hf)) return FALSE;
    proto_item_set_len(ti, xdr_getpos(xdrs) - start + VIR_HEADER_LEN);
    return TRUE;
}
static int hf_qemu_domain_agent_command_args__dom = -1;
static int hf_qemu_domain_agent_command_args__cmd = -1;
static int hf_qemu_domain_agent_command_args__timeout = -1;
static int hf_qemu_domain_agent_command_args__flags = -1;
static int hf_qemu_domain_agent_command_args = -1;
static gint ett_qemu_domain_agent_command_args = -1;
static gboolean dissect_xdr_qemu_domain_agent_command_args(tvbuff_t *tvb, proto_tree *tree, XDR *xdrs, int hf)
{
    goffset start;
    proto_item *ti;
    
    start = VIR_HEADER_LEN + xdr_getpos(xdrs);
    ti = proto_tree_add_item(tree, hf, tvb, start, -1, ENC_NA);
    proto_item_append_text(ti, " :: qemu_domain_agent_command_args");
    tree = proto_item_add_subtree(ti, ett_qemu_domain_agent_command_args);
    
    hf = hf_qemu_domain_agent_command_args__dom;
    if (!dissect_xdr_remote_nonnull_domain(tvb, tree, xdrs, hf)) return FALSE;
    
    hf = hf_qemu_domain_agent_command_args__cmd;
    if (!dissect_xdr_remote_nonnull_string(tvb, tree, xdrs, hf)) return FALSE;
    
    hf = hf_qemu_domain_agent_command_args__timeout;
    if (!dissect_xdr_int(tvb, tree, xdrs, hf)) return FALSE;
    
    hf = hf_qemu_domain_agent_command_args__flags;
    if (!dissect_xdr_u_int(tvb, tree, xdrs, hf)) return FALSE;
    proto_item_set_len(ti, xdr_getpos(xdrs) - start + VIR_HEADER_LEN);
    return TRUE;
}
static int hf_qemu_domain_agent_command_ret__result = -1;
static int hf_qemu_domain_agent_command_ret = -1;
static gint ett_qemu_domain_agent_command_ret = -1;
static gboolean dissect_xdr_qemu_domain_agent_command_ret(tvbuff_t *tvb, proto_tree *tree, XDR *xdrs, int hf)
{
    goffset start;
    proto_item *ti;
    
    start = VIR_HEADER_LEN + xdr_getpos(xdrs);
    ti = proto_tree_add_item(tree, hf, tvb, start, -1, ENC_NA);
    proto_item_append_text(ti, " :: qemu_domain_agent_command_ret");
    tree = proto_item_add_subtree(ti, ett_qemu_domain_agent_command_ret);
    
    hf = hf_qemu_domain_agent_command_ret__result;
    if (!dissect_xdr_remote_string(tvb, tree, xdrs, hf)) return FALSE;
    proto_item_set_len(ti, xdr_getpos(xdrs) - start + VIR_HEADER_LEN);
    return TRUE;
}
#define QEMU_PROGRAM (0x20008087)
#define QEMU_PROTOCOL_VERSION (1)
static const vir_dissector_index_t qemu_dissectors[] = {
    { 1, dissect_xdr_qemu_domain_monitor_command_args, dissect_xdr_qemu_domain_monitor_command_ret, NULL },
    { 2, dissect_xdr_qemu_domain_attach_args, dissect_xdr_qemu_domain_attach_ret, NULL },
    { 3, dissect_xdr_qemu_domain_agent_command_args, dissect_xdr_qemu_domain_agent_command_ret, NULL },
};
static const value_string qemu_procedure_strings[] = {
    { 1, "DOMAIN_MONITOR_COMMAND" },
    { 2, "DOMAIN_ATTACH" },
    { 3, "DOMAIN_AGENT_COMMAND" },
    { 0, NULL }
};
#endif /* _QEMU_H_ */
